Presentation/Areas/Admin/Controllers/MovieController.cs
using AutoMapper;
using DataAccess.Data;
using DataAccess.IRepositories;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Model.Constants;
using Model.DTOs;
using Model.Entitys;
using Model.Query;
using System.Diagnostics.Eventing.Reader;

namespace Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class MovieController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IMapper _mapper;
        private readonly MovieWebDbContext _db;
        public MovieController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment,IMapper mapper,MovieWebDbContext db)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
            _mapper = mapper;
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Upsert(Guid? Id)
        {
            UpdateMovieDTO vm = new()
            {
                movieDto = new MovieDTO(),
                actors = await _unitOfWork.Actor.ListAllAsync(new QueryOptions<Actor>()
                {
                    Includes = "Movies",
                }),
                genres = await _unitOfWork.Genre.ListAllAsync(new QueryOptions<Genre>()
                {
                    Includes = "Movies",
                }),
            };
            if (Id is null)
            {
                ViewBag.Action = "Add";
                return View(vm);
            }
            ViewBag.Action = "Update";
            Movie? movie = await _unitOfWork.Movie.GetAsync(new QueryOptions<Movie>()
            {
                Where=c=>c.MovieId.Equals(Id),
                Includes = "Actors,Genres"
            });
            if (movie is null)
            {
                return NotFound();
            }
            MovieDTO? movieDto = _mapper.Map<MovieDTO>(movie);

            if (movieDto is null)
            {
                return NotFound();
            }
            vm.movieDto = movieDto;


            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(MovieDTO movieDTO)
        {
            string WebRootPath = _hostEnvironment.WebRootPath;
            IFormFileCollection files = HttpContext.Request.Form.Files;
            if (files.Count > 0)
            {
                string fileName = Guid.NewGuid().ToString();
                string pathUploads = Path.Combine(WebRootPath, @"assets\images");
                string fileExtension = Path.GetExtension(files[0].FileName);
                if (movieDTO.ImageURL is not null)
                {
                    // this is an update
                    string imagePath = Path.Combine(WebRootPath, movieDTO.ImageURL.TrimStart('\\'));
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                }

                using (FileStream fs = new(
                    Path.Combine(pathUploads, fileName + fileExtension), FileMode.Create))
                {
                    await files[0].CopyToAsync(fs);
                }

                movieDTO.ImageURL = fileName + fileExtension;
            }
            if (movieDTO.MovieId== Guid.Empty)
            {
                Movie movie = _mapper.Map<Movie>(movieDTO);
                await _unitOfWork.Movie.AddNewGenreAsync(movie, movieDTO.GenreIds, _unitOfWork, _db);
                await _unitOfWork.Movie.AddNewActorAsync(movie, movieDTO.ActorIds, _unitOfWork, _db);

                _unitOfWork.Movie.Add(movie);
                await _unitOfWork.SaveAsync();
                TempData["success"] = "Thêm thành công !";
            }
            else
            {
                var movie = await _unitOfWork.Movie.GetAsync(new QueryOptions<Movie>()
                {
                    Where = c => c.MovieId.Equals(movieDTO.MovieId),
                    Includes = "Genres,Actors",
                }) ;
                movie.Title=movieDTO.Title;
                movie.Description=movieDTO.Description;
                movie.Language=movieDTO.Language;
                movie.ReleaseYear=movieDTO.ReleaseYear;
                movie.Director=movieDTO.Director;
                movie.ImageURL = movieDTO.ImageURL;
                movie.PosterURL= movieDTO.PosterURL;
                movie.TrailerURL= movieDTO.TrailerURL;
                movie.quality=movieDTO.quality;
                movie.MPAA=movieDTO.MPAA;
                movie.CreateDate=movieDTO.CreateDate;
                movie.MovieDuration=movieDTO.MovieDuration;
                movie.Released=movieDTO.Released;
                movie.IsSeriesMovie=movieDTO.IsSeriesMovie;

                await _unitOfWork.Movie.AddNewGenreAsync(movie, movieDTO.GenreIds, _unitOfWork,_db);
                await _unitOfWork.Movie.AddNewActorAsync(movie, movieDTO.ActorIds, _unitOfWork,_db);

                _unitOfWork.Movie.Update(movie);
                await _unitOfWork.SaveAsync();
                TempData["success"] = "Cập nhật thành công !";
            }
            return RedirectToAction("Index");
        }
        
        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAllMovie()
        {
            IEnumerable<Movie> movies = await _unitOfWork.Movie.ListAllAsync(new QueryOptions<Movie>()
            {
                Includes="Actors,Genres"
            });

            return Json(new
            {
                data = movies.Select(b => new
                {
                    b.MovieId,
                    b.Title,
                    Genres = b.Genres.Select(c=>c.GenreName),
                    Actors = b.Actors.Select(c => c.ActorName)
                })
            });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteMovie(Guid id)
        {
            Movie? movie = await _unitOfWork.Movie.GetAsync(id);
            if (movie is null)
            {
                return Json(new { success = false, message = "Lỗi khi xóa!" });
            }

            if (movie.ImageURL is not null)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                string imagePath = Path.Combine(webRootPath, movie.ImageURL.TrimStart('\\'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

             _unitOfWork.Movie.Remove(movie);
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteImage(Guid id)
        {
            Movie? movie = await _unitOfWork.Movie.GetAsync(id);
            if (movie is null)
            {
                return Json(new { success = false, message = "không tìm thấy phim!" });
            }

            if (movie.ImageURL is null)
            {
                return Json(new { success = false, message = "Không có ảnh!" });
            }

            string webRootPath = _hostEnvironment.WebRootPath;
            string imagePath = Path.Combine(webRootPath, movie.ImageURL.TrimStart('\\'));
            if (!System.IO.File.Exists(imagePath))
            {
                return Json(new { success = false, message = "Ảnh url Không còn tồn tại!" });
            }

            System.IO.File.Delete(imagePath);
            movie.ImageURL = null;
            _unitOfWork.Movie.Update(movie);


            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

Presentation/Controllers/MovieController.cs
using DataAccess.Data;
using DataAccess.IRepositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model.DTOs;
using Model.Entitys;
using Model.Query;

namespace Presentation.Controllers
{
    public class MovieController : Controller
    {
        private readonly IUnitOfWork _data;
        private readonly MovieWebDbContext _db;
        public MovieController(IUnitOfWork data, MovieWebDbContext db)
        {
            _data = data;
            _db = db;
        }
        public async Task<IActionResult> Detail(Guid? id)
        {
            var movies = await _data.Movie.ListAllAsync(new QueryOptions<Movie>()
            {
                Includes = "Genres, Actors, Ratings"
            });
            
            foreach (var movie in movies)
            {
                var listRating = await _data.Rating.ListAllAsync(new QueryOptions<Rating>()
                {
                    Includes = "Movie",
                    Where = c => c.MovieId.Equals(movie.MovieId)
                });
                if (listRating.Count() > 0)
                {
                    movie.AverageStar = listRating.Average(c => c.Stars);
                }
                else
                {
                    movie.AverageStar = 0;
                }
                
            }
            List<DisplayRating> ratings =new List<DisplayRating>();
            var users = _db.User.ToList();
            var movieee = (from a in movies
                        where a.MovieId.Equals(id)
                        select a).FirstOrDefault();
            if(movieee is null)
            {
                return NotFound();
            }
            if (users.Count() > 1)
            {
                foreach (var rate in movieee.Ratings)
                {
                    var rating = new DisplayRating();
                    var user = (from a in users
                                       where a.Id.Equals(rate.UserId)
                                       select a).FirstOrDefault();
                    if (user is null)
                        rating.fullName = "";
                    else
                        rating.fullName = (user.FirstName is null && user.LastName is null) ? user.UserName : user.FullName;
                    rating.rating = rate.Stars;
                    rating.Comment = rate.comment;
                    rating.RatingId=rate.RatingId;
                    ratings.Add(rating);
                }
            }
            DetailViewDTO vm = new DetailViewDTO()
            {
                movie = movieee,
                movies = movies,
                ratings = ratings
            };
            return View(vm);
        }
        public async Task<IActionResult> PlayMovie(Guid? Movieid, Guid? episodesId)
        {
            MoviePlayViewModel vm = new MoviePlayViewModel()
            {
                movies= await _data.Movie.ListAllAsync(new QueryOptions<Movie>()
                {
                    Includes = "Genres,Actors,Ratings",
                })
            };
            IEnumerable<MovieDetail> Listmovie = new List<MovieDetail>();
            if (Movieid.HasValue)
            {
                Listmovie = await _data.MovieDetail.ListAllAsync(new QueryOptions<MovieDetail>()
                {
                    Includes = "Movie",
                    Where = x => x.MovieId.Equals(Movieid),
                    OrderBy = x => x.MovieDetailName

                });
            }
             
            if (Listmovie.Count() <= 0)
                return NotFound();
            vm.movieDetails = Listmovie;
            if (episodesId != null)
            {
                var movie = await _data.MovieDetail.GetAsync(new QueryOptions<MovieDetail>()
                {
                    Includes = "Movie",
                    Where = x => x.MovieDetailId.Equals(episodesId),

                });
                vm.movieDetail = movie;
                
            }
            else
            {
                vm.movieDetail = vm.movieDetails.FirstOrDefault();
            }
            
            return View(vm);
        }
    }
}

Presentation/Controllers/RatingController.cs
using DataAccess.Data;
using DataAccess.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Model.Constants;
using Model.Entitys;
using System.Net;
using System.Security.Claims;

namespace Presentation.Controllers
{
    public class RatingController : Controller
    {
        private readonly IUnitOfWork _data;
        private readonly MovieWebDbContext _db;
        public RatingController(IUnitOfWork data, MovieWebDbContext db)
        {
            _data = data;
            _db = db;
        }
        [Authorize]
        public async Task<IActionResult> PostRating(int stars,string? comment,Guid MovieId)
        {
            ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
            Claim? claim = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier);
            var user = await _db.User.FindAsync(claim?.Value)
                ?? throw new Exception("User not found.");
            
            var ratings = new Rating()
            {
                MovieId = MovieId,
                Stars = stars,
                CreateDate = DateTime.Now,
                UserId=user.Id
            };
            if (comment is null)
            {
                ratings.comment = "";
             }
            else
                ratings.comment = comment;
            _data.Rating.Add(ratings);
            await _data.SaveAsync();
            return RedirectToAction("Detail","Movie",new { id=MovieId });
        }
        public async Task<IActionResult> DeleteRating(Guid id,Guid MovieId)
        {
            ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
            Claim? claim = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier);
            var user = await _db.User.FindAsync(claim?.Value)
                ?? throw new Exception("User not found.");
            var rating= await _data.Rating.GetAsync(id);
            if (rating == null)
            {
                return NotFound();
            }
            if (rating.UserId.Equals(user.Id)||user.Role.Equals(Roles.Admin))
            {
                _data.Rating.Remove(rating);
               await _data.SaveAsync();
            }
            else
            {
                return NotFound();
            }
            return RedirectToAction("Detail", "Movie", new { id = MovieId });
        }
    }
}

Presentation/Views/Movie/Detail.cshtml
@model DetailViewDTO
@using Microsoft.AspNetCore.Identity
@{
    ViewData["Title"] = "Detail";
}
@{
    var topRatedMovie = Model.movies.OrderByDescending(x => x.AverageStar).Take(4);
}

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<div>
    <section class="movie-detail" style="background-image: url('../../assets/images/upcoming-bg.png')">
        <div class="container">
            <nav style="--bs-breadcrumb-divider: '>>';" >
                <ol class="breadcrumb">
         
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Trang Chủ</a></li>
                    @if (Model.movie.IsSeriesMovie)
                    {

                        <li class="breadcrumb-item">Phim Bộ</li>
                      
                    }
                    else
                    {
                        <li class="breadcrumb-item">Phim Lẻ</li>
                    }
                    
                    <li class="breadcrumb-item">@Model.movie.Title</li>
                </ol>
            </nav>
        </div>
        <div class="container">
            @if (Model.movie.Released)
            {
                <a asp-area="" asp-controller="Movie" asp-action="PlayMovie" asp-route-Movieid="@Model.movie.MovieId">
                    <figure class="movie-detail-banner">
                
                <img src="~/assets/images/@Model.movie.ImageURL" alt="Free guy movie poster">

                <button class="play-btn">
                    <ion-icon name="play-circle-outline"></ion-icon>
                </button>

            </figure>
                </a>
            }
            else
            {
                <figure class="movie-detail-banner">
                
                <img src="~/assets/images/@Model.movie.ImageURL" alt="Free guy movie poster">

                
                </figure>
                
            }
            <div class="movie-detail-content" style="max-width: 820px">



                <h1 class="h1 detail-title">
                    <strong>@Model.movie.Title</strong>
                </h1>

                <div class="meta-wrapper">

                    <div class="badge-wrapper">
                        <div class="badge badge-fill">@Model.movie.MPAA</div>

                        <div class="badge badge-outline">@Model.movie.MovieDuration</div>
                    </div>

                    <div class="ganre-wrapper">
                        @foreach (var genre in Model.movie.Genres)
                        {
                            <a asp-area="" asp-controller="Book" asp-action="GetBookByCategory"
                               asp-route-id="@genre.GenreId">
                                <span class="badge rounded-pill bg-warning">@genre.GenreName</span>
                            </a>
                        }
                    </div>

                    <div class="date-time">

                        <div>
                            <ion-icon name="calendar-outline"></ion-icon>

                            <time datetime="2021">2021</time>
                        </div>

                        <div>
                            <ion-icon name="time-outline"></ion-icon>

                            <time datetime="PT115M">115 min</time>
                        </div>

                    </div>

                </div>



                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Nội Dung</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Diễn Viên</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Trailer</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-comment" type="button" role="tab" aria-controls="pills-comment" aria-selected="false">Bình Luận</button>
                    </li>
                </ul>
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">@Model.movie.Description</div>
                    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                        <div class="row align-items-start">
                        @foreach (var actor in Model.movie.Actors)
                        {
                                <div class="col-4 ">
                            <a asp-area="" asp-controller="Book" asp-action="GetBookByCategory"asp-route-id="@actor.ActorId"><span class="badge rounded-pill bg-warning">@actor.ActorName</span></a>
                            </div>
                        }
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                        <iframe width="900" height="500"
                                src="@Model.movie.TrailerURL.Replace($"watch?v=",$"embed/")">
                        </iframe>
                    </div>
                    <div class="tab-pane fade" id="pills-comment" role="tabpanel" aria-labelledby="pills-comment-tab">
                        <link rel="stylesheet" href="~/css/Comment.css">
                        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
                        <div class="container">
                            <div class="be-comment-block"> 
                               @if(Model.ratings.Count()>0){
                                @foreach (var rate in Model.ratings){
                                <div class="be-comment">
                                    <div class="be-img-comment">
                                    </div>
                                    <div class="be-comment-content">

                                        <span class="be-comment-name">
                                            <a href="blog-detail-2.html">@rate.fullName</a>
                                        </span>
                                        <span class="">
                                                    @if(rate.rating!=0){
                                                    @for (int i = 1; i <= rate.rating; i++)
                                                    {
                                                        <i class="bi bi-star-fill"></i>
                                                    }
                                                    }
                                        </span>

                                        <p class="be-comment-text">
                                            @rate.Comment
                                        </p>
                                                @if (SignInManager.IsSignedIn(User))
                                                {
                                                    <a asp-controller="Rating" asp-action="DeleteRating" asp-route-id="@rate.RatingId" asp-route-MovieId="@Model.movie.MovieId" class="btn btn-danger " style="width:70px;height:32px;font-size:10px;padding-left:10px">Delete</a>
                                                }
                                            </div>
                                </div>
                                }}
                                <form asp-controller="Rating" asp-action="PostRating" method="post" asp-route-MovieId="@Model.movie.MovieId">
                                    <div class="stars" for="stars" id="stars">
                                        <input class="star star-5" id="star-5" type="radio" name="stars" value="5" />

                                        <label class="star star-5" for="star-5"></label>

                                        <input class="star star-4" id="star-4" type="radio" name="stars" value="4" />

                                        <label class="star star-4" for="star-4"></label>

                                        <input class="star star-3" id="star-3" type="radio" name="stars" value="3" />

                                        <label class="star star-3" for="star-3"></label>

                                        <input class="star star-2" id="star-2" type="radio" name="stars" value="2" />

                                        <label class="star star-2" for="star-2"></label>

                                        <input class="star star-1" id="star-1" type="radio" name="stars" value="1" />

                                        <label class="star star-1" for="star-1"></label>
                                    </div>


                                    <div class="row">
                                        <input type="text" class="form-control-comment" id="comment" name="comment" placeholder="Enter your comment...">
                                    </div>
                                    <div class=" p-2">
                                        <div class="mt-2 text-right"><button class="btn btn-primary btn-sm shadow-none" type="submit">Bình luận</button></div>
                                    </div>
                                </form>
                                

                                    
                             </div>
                            
                                
                            
                    </div>
                </div>

            </div>


        </div>
    </section>

    

    <section class="top-rated">
        <div class="container">

            <p class="section-subtitle">Online Streaming</p>

            <h2 class="h2 section-title">Top Rated Movies</h2>

            <ul class="filter-list">

                <li>
                    <button class="filter-btn">Movies</button>
                </li>

                <li>
                    <button class="filter-btn">TV Shows</button>
                </li>

                <li>
                    <button class="filter-btn">Documentary</button>
                </li>

                <li>
                    <button class="filter-btn">Sports</button>
                </li>

            </ul>

            <ul class="movies-list">
                @foreach (var movie in topRatedMovie)
                {
                    <li>
                        <div class="movie-card">

                            <a asp-controller="Movie" asp-action="Detail" asp-route-id="@movie.MovieId">
                                <figure class="card-banner">
                                    <img src="~/assets/images/@movie.ImageURL" alt="Sonic the Hedgehog 2 movie poster">
                                </figure>
                            </a>

                            <div class="title-wrapper">
                                <a asp-controller="Movie" asp-action="Detail" asp-route-id="@movie.MovieId">
                                    <h3 class="card-title">@movie.Title</h3>
                                </a>

                                <time datetime="2022">@movie.ReleaseYear</time>
                            </div>

                            <div class="card-meta">
                                <div class="badge badge-outline">@movie.quality</div>

                                <div class="duration">
                                    <ion-icon name="time-outline"></ion-icon>

                                    <time datetime="PT122M">@movie.MovieDuration min</time>
                                </div>

                                <div class="rating">
                                    <ion-icon name="star"></ion-icon>

                                    <data>@movie.AverageStar</data>
                                </div>
                            </div>

                        </div>
                    </li>
                }

            </ul>

        </div>
    </section>

</div>