Presentation/Areas/Admin/Controllers/ActorController.cs
using AutoMapper;
using DataAccess.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Model.Constants;
using Model.DTOs;
using Model.Entitys;
using Model.Query;

namespace Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class ActorController : Controller
    {
        private readonly IUnitOfWork _data;
        private readonly IMapper _mapper;
        public ActorController(IUnitOfWork data, IMapper mapper)
        {
            _data = data;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Upsert(Guid? id)
        {
            ActorDTO? actorDTO = new();

            // for add
            if (id is null)
            {
                ViewBag.Action = "Add";
                return View(actorDTO);
            }

            // for update
            ViewBag.Action = "Update";
            actorDTO = _mapper.Map<ActorDTO>(await _data.Actor.GetAsync(id.GetValueOrDefault()));
            if (actorDTO is null)
            {
                return NotFound();
            }
            return View(actorDTO);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ActorDTO actorDTO)
        {
            var ExistCategory = await _data.Actor.GetByIdAsync(c => c.ActorId.Equals(actorDTO.ActorId));
            var actor = _mapper.Map<Actor>(actorDTO);
            if (ExistCategory is null)
            {
                _data.Actor.Add(actor);
                await _data.SaveAsync();
                TempData["success"] = "Thêm thành công !";
            }
            else
            {

                _data.Actor.Update(actor);

                await _data.SaveAsync();
                TempData["success"] = "Cập nhật thành công !";
            }
            return RedirectToAction(nameof(Index));
        }
        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAllActor()
        {
            return Json(new
            {
                data = await _data.Actor.ListAllAsync(new QueryOptions<Actor>()
                {
                })
            });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteActor(Guid id)
        {
            Actor? actor = await _data.Actor.GetAsync(id);
            if (actor is null)
            {
                return Json(new { success = false, message = "Không tìm thấy diễn viên bạn muốn xóa." });
            }

            _data.Actor.Remove(actor);
            await _data.SaveAsync();
            return Json(new { success = true, message = "Đã Xóa thành công." });
        }

        #endregion
    }
}

Presentation/Areas/Admin/Controllers/GenreController.cs
using AutoMapper;
using DataAccess.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Model.Constants;
using Model.DTOs;
using Model.Entitys;
using Model.Query;

namespace Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class GenreController : Controller
    {
        
        private readonly IUnitOfWork _data;
        private readonly IMapper _mapper;
        public GenreController(IUnitOfWork data,IMapper mapper)
        {
            _data = data;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Upsert(Guid? id)
        {
            GenreDTO? genreDTO = new();

            // for add
            if (id is null)
            {
                ViewBag.Action = "Add";
                return View(genreDTO);
            }

            // for update
            ViewBag.Action = "Update";
            genreDTO = _mapper.Map<GenreDTO>(await _data.Genre.GetAsync(id.GetValueOrDefault()));
            if (genreDTO is null)
            {
                return NotFound();
            }
            return View(genreDTO);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(GenreDTO genreDTO)
        {
            var ExistCategory = await _data.Genre.GetByIdAsync(c => c.GenreId.Equals(genreDTO.GenreId) );
            var genre = _mapper.Map<Genre>(genreDTO);
            if (ExistCategory is null)
            {
                 _data.Genre.Add(genre);
              await  _data.SaveAsync();
                TempData["success"] = "Thêm thành công !";
            }
            else
            {
                
                 _data.Genre.Update(genre);

               await _data.SaveAsync();
                TempData["success"] = "Cập nhật thành công !";
            }
            return RedirectToAction(nameof(Index));
        }
        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAllGenre()
        {
            return Json(new { data = await _data.Genre.ListAllAsync(new QueryOptions<Genre>()
            {
            })
        });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteGenre(Guid id)
        {
            Genre? genre = await _data.Genre.GetAsync(id);
            if (genre is null)
            {
                return Json(new { success = false, message = "Không tìm thấy thể loại bạn muốn xóa." });
            }

             _data.Genre.Remove(genre);
           await _data.SaveAsync();
            return Json(new { success = true, message = "Đã Xóa thành công." });
        }

        #endregion
    }
}

Presentation/Areas/Admin/Controllers/MovieController.cs
using AutoMapper;
using DataAccess.Data;
using DataAccess.IRepositories;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Model.Constants;
using Model.DTOs;
using Model.Entitys;
using Model.Query;
using System.Diagnostics.Eventing.Reader;

namespace Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class MovieController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IMapper _mapper;
        private readonly MovieWebDbContext _db;
        public MovieController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment,IMapper mapper,MovieWebDbContext db)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
            _mapper = mapper;
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Upsert(Guid? Id)
        {
            UpdateMovieDTO vm = new()
            {
                movieDto = new MovieDTO(),
                actors = await _unitOfWork.Actor.ListAllAsync(new QueryOptions<Actor>()
                {
                    Includes = "Movies",
                }),
                genres = await _unitOfWork.Genre.ListAllAsync(new QueryOptions<Genre>()
                {
                    Includes = "Movies",
                }),
            };
            if (Id is null)
            {
                ViewBag.Action = "Add";
                return View(vm);
            }
            ViewBag.Action = "Update";
            Movie? movie = await _unitOfWork.Movie.GetAsync(new QueryOptions<Movie>()
            {
                Where=c=>c.MovieId.Equals(Id),
                Includes = "Actors,Genres"
            });
            if (movie is null)
            {
                return NotFound();
            }
            MovieDTO? movieDto = _mapper.Map<MovieDTO>(movie);

            if (movieDto is null)
            {
                return NotFound();
            }
            vm.movieDto = movieDto;


            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(MovieDTO movieDTO)
        {
            string WebRootPath = _hostEnvironment.WebRootPath;
            IFormFileCollection files = HttpContext.Request.Form.Files;
            if (files.Count > 0)
            {
                string fileName = Guid.NewGuid().ToString();
                string pathUploads = Path.Combine(WebRootPath, @"assets\images");
                string fileExtension = Path.GetExtension(files[0].FileName);
                if (movieDTO.ImageURL is not null)
                {
                    // this is an update
                    string imagePath = Path.Combine(WebRootPath, movieDTO.ImageURL.TrimStart('\\'));
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                }

                using (FileStream fs = new(
                    Path.Combine(pathUploads, fileName + fileExtension), FileMode.Create))
                {
                    await files[0].CopyToAsync(fs);
                }

                movieDTO.ImageURL = fileName + fileExtension;
            }
            if (movieDTO.MovieId== Guid.Empty)
            {
                Movie movie = _mapper.Map<Movie>(movieDTO);
                await _unitOfWork.Movie.AddNewGenreAsync(movie, movieDTO.GenreIds, _unitOfWork, _db);
                await _unitOfWork.Movie.AddNewActorAsync(movie, movieDTO.ActorIds, _unitOfWork, _db);

                _unitOfWork.Movie.Add(movie);
                await _unitOfWork.SaveAsync();
                TempData["success"] = "Thêm thành công !";
            }
            else
            {
                var movie = await _unitOfWork.Movie.GetAsync(new QueryOptions<Movie>()
                {
                    Where = c => c.MovieId.Equals(movieDTO.MovieId),
                    Includes = "Genres,Actors",
                }) ;
                movie.Title=movieDTO.Title;
                movie.Description=movieDTO.Description;
                movie.Language=movieDTO.Language;
                movie.ReleaseYear=movieDTO.ReleaseYear;
                movie.Director=movieDTO.Director;
                movie.ImageURL = movieDTO.ImageURL;
                movie.PosterURL= movieDTO.PosterURL;
                movie.TrailerURL= movieDTO.TrailerURL;
                movie.quality=movieDTO.quality;
                movie.MPAA=movieDTO.MPAA;
                movie.CreateDate=movieDTO.CreateDate;
                movie.MovieDuration=movieDTO.MovieDuration;
                movie.Released=movieDTO.Released;
                movie.IsSeriesMovie=movieDTO.IsSeriesMovie;

                await _unitOfWork.Movie.AddNewGenreAsync(movie, movieDTO.GenreIds, _unitOfWork,_db);
                await _unitOfWork.Movie.AddNewActorAsync(movie, movieDTO.ActorIds, _unitOfWork,_db);

                _unitOfWork.Movie.Update(movie);
                await _unitOfWork.SaveAsync();
                TempData["success"] = "Cập nhật thành công !";
            }
            return RedirectToAction("Index");
        }
        
        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAllMovie()
        {
            IEnumerable<Movie> movies = await _unitOfWork.Movie.ListAllAsync(new QueryOptions<Movie>()
            {
                Includes="Actors,Genres"
            });

            return Json(new
            {
                data = movies.Select(b => new
                {
                    b.MovieId,
                    b.Title,
                    Genres = b.Genres.Select(c=>c.GenreName),
                    Actors = b.Actors.Select(c => c.ActorName)
                })
            });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteMovie(Guid id)
        {
            Movie? movie = await _unitOfWork.Movie.GetAsync(id);
            if (movie is null)
            {
                return Json(new { success = false, message = "Lỗi khi xóa!" });
            }

            if (movie.ImageURL is not null)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                string imagePath = Path.Combine(webRootPath, movie.ImageURL.TrimStart('\\'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

             _unitOfWork.Movie.Remove(movie);
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteImage(Guid id)
        {
            Movie? movie = await _unitOfWork.Movie.GetAsync(id);
            if (movie is null)
            {
                return Json(new { success = false, message = "không tìm thấy phim!" });
            }

            if (movie.ImageURL is null)
            {
                return Json(new { success = false, message = "Không có ảnh!" });
            }

            string webRootPath = _hostEnvironment.WebRootPath;
            string imagePath = Path.Combine(webRootPath, movie.ImageURL.TrimStart('\\'));
            if (!System.IO.File.Exists(imagePath))
            {
                return Json(new { success = false, message = "Ảnh url Không còn tồn tại!" });
            }

            System.IO.File.Delete(imagePath);
            movie.ImageURL = null;
            _unitOfWork.Movie.Update(movie);


            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

Presentation/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using DataAccess.Data;
using DataAccess.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model.Constants;
using Model.DTOs;
using Model.Entitys;

namespace Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _data;
        private readonly IMapper _mapper;
        private readonly MovieWebDbContext _db;
        public UserController(IUnitOfWork data, IMapper mapper,MovieWebDbContext db)
        {
            _data = data;
            _mapper = mapper;
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region API CALLS

        public async Task<IActionResult> GetAllUsers()
        {
            List<User> users = await _db.User.ToListAsync();

            // this will be the mapping between the users and the roles
            List<IdentityUserRole<string>> userRoles = await _db.UserRoles.ToListAsync();

            List<IdentityRole> roles = await _db.Roles.ToListAsync();

            // maping users
            List<UserDTO> customerDtos = new();

            foreach (var user in users)
            {
                string roleId = userRoles.FirstOrDefault(ur => ur.UserId == user.Id)?.RoleId ?? string.Empty;
                // add role for the user in users
                user.Role = roles.FirstOrDefault(r => r.Id == roleId)?.Name ?? string.Empty;

                UserDTO userDto = new()
                {
                    Id = user.Id,
                    Email = user.Email ?? string.Empty,
                    PhoneNumber = user.PhoneNumber ?? string.Empty,
                    Role = user.Role,
                    LockoutEnd = user.LockoutEnd?.UtcDateTime ?? null,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                };
                customerDtos.Add(userDto);
            }

            return Json(new { data = customerDtos });
        }

        [HttpGet]
        public async Task<IActionResult> LockUnlockUser(string id)
        {
            var user = await _db.Users.FirstOrDefaultAsync(u => u.Id == id);

            if (user is null)
            {
                return Json(new { success = false, message = "Không tìm thấy dữ liệu." });
            }

            DateTime currentDate = DateTime.Today;
            DateTime lockoutEndDate = user.LockoutEnd?.UtcDateTime ?? new DateTime(1000, 1, 1);

            if (lockoutEndDate > currentDate)
            {
                // unlock it
                user.LockoutEnd = currentDate.AddYears(-100);
                await _db.SaveChangesAsync();

                return Json(new { success = true, message = "Đã mở khóa." });
            }
            else
            {
                // lock it
                user.LockoutEnd = currentDate.AddYears(100);
                await _db.SaveChangesAsync();

                return Json(new { success = true, message = "Đã khóa." });
            }
        }

        #endregion
    }
}

Presentation/Views/Shared/_ActionOrReturnPartial.cshtml
<div class="mb-3 row">
    <div class="col-md-6 offset-md-3">
        @if (ViewBag.Action == "Add")
        {
            <div class="row">
                <div class="col-md mb-2">
                    <button type="submit" class="btn btn-primary form-control">
                        Tạo
                    </button>
                </div>
                <div class="col-md">
                    <a asp-action="Index" class="btn btn-secondary form-control">
                        Quay Lại
                    </a>
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col-md mb-2">
                    <button type="submit" class="btn btn-primary form-control">
                        Chỉnh Sửa
                    </button>
                </div>
                <div class="col-md">
                    <a class="btn btn-secondary form-control" asp-action="Index">
                        Quay Lại
                    </a>
                </div>
            </div>
        }
    </div>
</div>

Presentation/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootstrap 5 Simple Admin Dashboard</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/css/AdminSite .css">
</head>
<body>
    <nav class="navbar navbar-light bg-light p-3">
        <div class="d-flex col-12 col-md-3 col-lg-2 mb-2 mb-lg-0 flex-wrap flex-md-nowrap justify-content-between">
            <a class="navbar-brand" href="#">
                Trang Quản Lý
            </a>
            <button class="navbar-toggler d-md-none collapsed mb-3" type="button" data-toggle="collapse" data-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        
        <div class="col-12 col-md-5 col-lg-8 d-flex align-items-center justify-content-md-end mt-3 mt-md-0">
            
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
                        Hello @UserManager.GetUserName(User)!
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">Manager</a></li>
                    </ul>
                </div>
            }
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-area="Admin" asp-controller="Home" asp-action="Index">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                            <span class="ml-2">Dashboard</span>
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" asp-area="Admin" asp-controller="Movie" asp-action="Index">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 4H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1Zm0 0-4 4m5 0H4m1 0 4-4m1 4 4-4m-4 7v6l4-3-4-3Z" />
                                </svg>

                            <span class="ml-2">Phim</span>
                          </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Genre" asp-action="Index">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 5v14M9 5v14M4 5h16a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Z" />
                                </svg>

                            <span class="ml-2">Thể Loại</span>
                          </a>
                        </li>
                        <li class="nav-item" >
                            <a class="nav-link" asp-area="Admin" asp-controller="Actor" asp-action="Index">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                            <span class="ml-2">Diễn Viên</span>
                          </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z" clip-rule="evenodd" />
                                </svg>

                            <span class="ml-2">Người Dùng</span>
                          </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="MovieEpisode" asp-action="Index">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M6 5a2 2 0 0 1 2-2h4.157a2 2 0 0 1 1.656.879L15.249 6H19a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2v-5a3 3 0 0 0-3-3h-3.22l-1.14-1.682A3 3 0 0 0 9.157 6H6V5Z" clip-rule="evenodd" />
                                    <path fill-rule="evenodd" d="M3 9a2 2 0 0 1 2-2h4.157a2 2 0 0 1 1.656.879L12.249 10H3V9Zm0 3v7a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2v-7H3Z" clip-rule="evenodd" />
                                </svg>


                                <span class="ml-2">Tập</span>
                            </a>
                        </li>
                      </ul>
                </div>
            </nav>
            <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">
                @RenderBody()
            
            <footer class="pt-5 d-flex justify-content-between">
                    <span>Copyright © 2019-2020 <a href="https://themesberg.com">Themesberg</a></span>
                    <ul class="nav m-0">
                        <li class="nav-item">
                          <a class="nav-link text-secondary" aria-current="page" href="#">Privacy Policy</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link text-secondary" href="#">Terms and conditions</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link text-secondary" href="#">Contact</a>
                        </li>
                      </ul>
                </footer>
            </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/Views/Shared/_Pagination.cshtml
@model Pager
@{
}
<div class="container">
    <ul class="pagination justify-content-end">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item ">
                <a class="page-link" asp-controller="Home" asp-action="ListAllMovie" asp-route-page="1">Đầu</a>
            </li>
            <li class="page-item ">
                <a class="page-link" asp-controller="Home" asp-action="ListAllMovie" asp-route-page="@(Model.CurrentPage-1)">Trước</a>
            </li>

        }
        @if (Model.TotalPage > 0)
        {

            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge==Model.CurrentPage?"active":"") ">
                    <a class="page-link" asp-controller="Home" asp-action="ListAllMovie" asp-route-page="@pge">@pge</a>
                </li>
            }

        }
        @if (Model.CurrentPage < Model.TotalPage)
        {
            <li class="page-item ">
                <a class="page-link" asp-controller="Home" asp-action="ListAllMovie" asp-route-page="@(Model.CurrentPage+1)">Sau</a>
            </li>
            <li class="page-item ">
                <a class="page-link" asp-controller="Home" asp-action="ListAllMovie" asp-route-page="@(Model.TotalPage)">Cuối</a>
            </li>
        }
    </ul>
</div>